*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 08:57:53 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.30.1.26:5000 fd 3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Python main interpreter initialized at 0x1b61468
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 359920 bytes (351 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x1b61468 pid: 28754 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 28754)
spawned uWSGI worker 1 (pid: 28758, cores: 2)
spawned uWSGI worker 2 (pid: 28760, cores: 2)
spawned uWSGI worker 3 (pid: 28762, cores: 2)
spawned uWSGI worker 4 (pid: 28764, cores: 2)
[pid: 28764|app: 0|req: 1/1] 121.133.232.153 () {32 vars in 655 bytes} [Mon Oct 31 08:58:41 2022] GET / => generated 327 bytes in 61 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 28760|app: 0|req: 1/2] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 08:58:42 2022] GET /get_cam => generated 462 bytes in 62 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 28764|app: 0|req: 3/3] 121.133.232.153 () {32 vars in 655 bytes} [Mon Oct 31 08:58:51 2022] GET / => generated 327 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 28762|app: 0|req: 1/4] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 08:58:53 2022] GET /get_cam => generated 462 bytes in 37 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
[2022-10-31 08:58:55,120] ERROR in app: Exception on /video_feed [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./raspi_web.py", line 34, in video_feed
    return Response(gen(RealSense()), mimetype='multipart/x-mixed-replace; boundary=frame')
  File "./realsense.py", line 18, in __init__
    self.pipeline.start(config)
RuntimeError: failed to set power state
[pid: 28762|app: 0|req: 2/5] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 08:58:53 2022] GET /video_feed => generated 291 bytes in 1602 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
[pid: 28762|app: 0|req: 3/6] 121.133.232.153 () {36 vars in 742 bytes} [Mon Oct 31 09:00:49 2022] GET /get_cam => generated 462 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
[2022-10-31 09:00:52,237] ERROR in app: Exception on /video_feed [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./raspi_web.py", line 34, in video_feed
    return Response(gen(RealSense()), mimetype='multipart/x-mixed-replace; boundary=frame')
  File "./realsense.py", line 18, in __init__
    self.pipeline.start(config)
RuntimeError: failed to set power state
[pid: 28760|app: 0|req: 2/7] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 09:00:50 2022] GET /video_feed => generated 291 bytes in 2001 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 1)
[pid: 28760|app: 0|req: 3/8] 121.133.232.153 () {32 vars in 655 bytes} [Mon Oct 31 09:03:41 2022] GET / => generated 327 bytes in 3 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
Mon Oct 31 09:03:41 2022 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed (121.133.232.153)
OSError: write error
[pid: 28762|app: 0|req: 4/9] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 09:03:53 2022] GET /get_cam => generated 462 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 28762|app: 0|req: 5/10] 121.133.232.153 () {32 vars in 655 bytes} [Mon Oct 31 09:03:59 2022] GET / => generated 327 bytes in 3 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
Mon Oct 31 09:04:00 2022 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
Mon Oct 31 09:04:00 2022 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed (121.133.232.153)
OSError: write error
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 2 seconds
worker 4 buried after 2 seconds
Mon Oct 31 09:05:16 2022 - worker 2 (pid: 28760) is taking too much time to die...NO MERCY !!!
Mon Oct 31 09:05:16 2022 - worker 3 (pid: 28762) is taking too much time to die...NO MERCY !!!
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 09:09:30 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.30.1.26:5000 fd 3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Python main interpreter initialized at 0x1236468
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 359920 bytes (351 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x1236468 pid: 29813 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 29813)
spawned uWSGI worker 1 (pid: 29844, cores: 2)
spawned uWSGI worker 2 (pid: 29846, cores: 2)
spawned uWSGI worker 3 (pid: 29848, cores: 2)
spawned uWSGI worker 4 (pid: 29850, cores: 2)
[pid: 29850|app: 0|req: 1/1] 121.133.232.153 () {32 vars in 655 bytes} [Mon Oct 31 09:09:38 2022] GET / => generated 327 bytes in 30 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 29850|app: 0|req: 2/2] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 09:09:39 2022] GET /get_cam => generated 462 bytes in 7 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 870, in __next__
    return self._next()
  File "/usr/lib/python3/dist-packages/werkzeug/wrappers.py", line 82, in _iter_encoded
    for item in iterable:
  File "./raspi_web.py", line 21, in gen
    frame = camera.get_numpy_color_image()
  File "./realsense.py", line 21, in get_numpy_color_image
    frames = self.pipeline.wait_for_frames()
RuntimeError: Frame didn't arrive within 5000
[pid: 29844|app: 0|req: 1/3] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 09:09:40 2022] GET /video_feed => generated 0 bytes in 5021 msecs (HTTP/1.1 200) 4 headers in 158 bytes (0 switches on core 0)
[pid: 29850|app: 0|req: 3/4] 121.133.232.153 () {36 vars in 742 bytes} [Mon Oct 31 09:09:50 2022] GET /get_cam => generated 462 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 870, in __next__
    return self._next()
  File "/usr/lib/python3/dist-packages/werkzeug/wrappers.py", line 82, in _iter_encoded
    for item in iterable:
  File "./raspi_web.py", line 21, in gen
    frame = camera.get_numpy_color_image()
  File "./realsense.py", line 21, in get_numpy_color_image
    frames = self.pipeline.wait_for_frames()
RuntimeError: Frame didn't arrive within 5000
[pid: 29848|app: 0|req: 1/5] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 09:09:50 2022] GET /video_feed => generated 0 bytes in 5022 msecs (HTTP/1.1 200) 4 headers in 158 bytes (0 switches on core 0)
[pid: 29848|app: 0|req: 2/6] 121.133.232.153 () {32 vars in 655 bytes} [Mon Oct 31 09:10:19 2022] GET / => generated 327 bytes in 22 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 2 seconds
worker 2 buried after 2 seconds
worker 3 buried after 2 seconds
worker 4 buried after 2 seconds
goodbye to uWSGI.
!!! uWSGI process 29813 got Segmentation Fault !!!
*** backtrace of 29813 ***
*** end of backtrace ***
*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 09:13:34 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.30.1.26:5000 fd 3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Python main interpreter initialized at 0x1768468
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 359920 bytes (351 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x1768468 pid: 30025 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 30025)
spawned uWSGI worker 1 (pid: 30054, cores: 2)
spawned uWSGI worker 2 (pid: 30056, cores: 2)
spawned uWSGI worker 3 (pid: 30058, cores: 2)
spawned uWSGI worker 4 (pid: 30060, cores: 2)
[pid: 30056|app: 0|req: 1/1] 121.133.232.153 () {34 vars in 686 bytes} [Mon Oct 31 09:13:49 2022] GET / => generated 327 bytes in 30 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 30060|app: 0|req: 1/2] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 09:13:51 2022] GET /get_cam => generated 462 bytes in 38 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 870, in __next__
    return self._next()
  File "/usr/lib/python3/dist-packages/werkzeug/wrappers.py", line 82, in _iter_encoded
    for item in iterable:
  File "./raspi_web.py", line 21, in gen
    frame = cam.get_numpy_color_image()
  File "./realsense.py", line 21, in get_numpy_color_image
    frames = self.pipeline.wait_for_frames()
RuntimeError: Frame didn't arrive within 5000
[pid: 30060|app: 0|req: 2/3] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 09:13:51 2022] GET /video_feed => generated 0 bytes in 5014 msecs (HTTP/1.1 200) 4 headers in 158 bytes (0 switches on core 1)
[pid: 30058|app: 0|req: 1/4] 121.133.232.153 () {36 vars in 742 bytes} [Mon Oct 31 09:14:16 2022] GET /get_cam => generated 462 bytes in 37 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 870, in __next__
    return self._next()
  File "/usr/lib/python3/dist-packages/werkzeug/wrappers.py", line 82, in _iter_encoded
    for item in iterable:
  File "./raspi_web.py", line 21, in gen
    frame = cam.get_numpy_color_image()
  File "./realsense.py", line 21, in get_numpy_color_image
    frames = self.pipeline.wait_for_frames()
RuntimeError: Frame didn't arrive within 5000
[pid: 30060|app: 0|req: 3/5] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 09:14:17 2022] GET /video_feed => generated 0 bytes in 5005 msecs (HTTP/1.1 200) 4 headers in 158 bytes (0 switches on core 0)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 2 seconds
worker 2 buried after 2 seconds
worker 3 buried after 2 seconds
worker 4 buried after 2 seconds
goodbye to uWSGI.
!!! uWSGI process 30025 got Segmentation Fault !!!
*** backtrace of 30025 ***
*** end of backtrace ***
*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 09:17:57 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.30.1.26:5000 fd 3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Python main interpreter initialized at 0x16a9468
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 359920 bytes (351 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x16a9468 pid: 30288 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 30288)
spawned uWSGI worker 1 (pid: 30295, cores: 2)
spawned uWSGI worker 2 (pid: 30297, cores: 2)
spawned uWSGI worker 3 (pid: 30299, cores: 2)
spawned uWSGI worker 4 (pid: 30301, cores: 2)
[pid: 30301|app: 0|req: 1/1] 121.133.232.153 () {36 vars in 742 bytes} [Mon Oct 31 09:18:02 2022] GET /get_cam => generated 462 bytes in 29 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 30299|app: 0|req: 1/2] 121.133.232.153 () {34 vars in 679 bytes} [Mon Oct 31 09:18:18 2022] GET / => generated 327 bytes in 33 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 30301|app: 0|req: 2/3] 121.133.232.153 () {32 vars in 655 bytes} [Mon Oct 31 09:18:18 2022] GET / => generated 327 bytes in 3 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
[pid: 30301|app: 0|req: 3/4] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 09:18:20 2022] GET /get_cam => generated 462 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 870, in __next__
    return self._next()
  File "/usr/lib/python3/dist-packages/werkzeug/wrappers.py", line 82, in _iter_encoded
    for item in iterable:
  File "./raspi_web.py", line 20, in gen
    camera = RealSense()
  File "./realsense.py", line 18, in __init__
    self.pipeline.start(config)
RuntimeError: failed to set power state
[pid: 30301|app: 0|req: 4/5] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 09:18:20 2022] GET /video_feed => generated 0 bytes in 1860 msecs (HTTP/1.1 200) 4 headers in 158 bytes (0 switches on core 1)
[pid: 30301|app: 0|req: 5/6] 121.133.232.153 () {36 vars in 742 bytes} [Mon Oct 31 09:18:34 2022] GET /get_cam => generated 462 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 30299|app: 0|req: 2/7] 121.133.232.153 () {34 vars in 704 bytes} [Mon Oct 31 09:19:06 2022] GET / => generated 327 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
Mon Oct 31 09:19:06 2022 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
Mon Oct 31 09:19:06 2022 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed (121.133.232.153)
OSError: write error
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
worker 4 buried after 2 seconds
Mon Oct 31 09:20:13 2022 - worker 2 (pid: 30297) is taking too much time to die...NO MERCY !!!
Mon Oct 31 09:20:13 2022 - worker 3 (pid: 30299) is taking too much time to die...NO MERCY !!!
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 09:20:53 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.30.1.26:5000 fd 3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Python main interpreter initialized at 0x1917468
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 359920 bytes (351 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x1917468 pid: 30677 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 30677)
spawned uWSGI worker 1 (pid: 30709, cores: 2)
spawned uWSGI worker 2 (pid: 30711, cores: 2)
spawned uWSGI worker 3 (pid: 30713, cores: 2)
spawned uWSGI worker 4 (pid: 30715, cores: 2)
[pid: 30711|app: 0|req: 1/1] 121.133.232.153 () {36 vars in 735 bytes} [Mon Oct 31 09:20:57 2022] GET / => generated 327 bytes in 30 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 30713|app: 0|req: 1/2] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 09:20:59 2022] GET /get_cam => generated 462 bytes in 37 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 870, in __next__
    return self._next()
  File "/usr/lib/python3/dist-packages/werkzeug/wrappers.py", line 82, in _iter_encoded
    for item in iterable:
  File "./raspi_web.py", line 22, in gen
    frame = camera.get_numpy_color_image()
  File "./realsense.py", line 21, in get_numpy_color_image
    frames = self.pipeline.wait_for_frames()
RuntimeError: Frame didn't arrive within 5000
[pid: 30709|app: 0|req: 1/3] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 09:20:59 2022] GET /video_feed => generated 0 bytes in 5021 msecs (HTTP/1.1 200) 4 headers in 158 bytes (0 switches on core 0)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 2 seconds
worker 2 buried after 2 seconds
worker 3 buried after 2 seconds
worker 4 buried after 2 seconds
goodbye to uWSGI.
!!! uWSGI process 30677 got Segmentation Fault !!!
*** backtrace of 30677 ***
*** end of backtrace ***
*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 09:21:31 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.30.1.26:5000 fd 3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Python main interpreter initialized at 0x129a468
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 359920 bytes (351 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x129a468 pid: 30769 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 30769)
spawned uWSGI worker 1 (pid: 30803, cores: 2)
spawned uWSGI worker 2 (pid: 30805, cores: 2)
spawned uWSGI worker 3 (pid: 30807, cores: 2)
spawned uWSGI worker 4 (pid: 30809, cores: 2)
[pid: 30807|app: 0|req: 1/1] 121.133.232.153 () {32 vars in 655 bytes} [Mon Oct 31 09:21:37 2022] GET / => generated 327 bytes in 31 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 30809|app: 0|req: 1/2] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 09:21:38 2022] GET /get_cam => generated 462 bytes in 35 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 870, in __next__
    return self._next()
  File "/usr/lib/python3/dist-packages/werkzeug/wrappers.py", line 82, in _iter_encoded
    for item in iterable:
  File "./raspi_web.py", line 23, in gen
    frame = camera.get_numpy_color_image()
  File "./realsense.py", line 21, in get_numpy_color_image
    frames = self.pipeline.wait_for_frames()
RuntimeError: Frame didn't arrive within 5000
[pid: 30807|app: 0|req: 2/3] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 09:21:38 2022] GET /video_feed => generated 0 bytes in 5014 msecs (HTTP/1.1 200) 4 headers in 158 bytes (0 switches on core 1)
uwsgi_proto_http_parser(): Connection reset by peer [proto/http.c line 463]
[pid: 30809|app: 0|req: 2/4] 167.248.133.62 () {20 vars in 214 bytes} [Mon Oct 31 09:25:05 2022] GET / => generated 327 bytes in 4 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 30805|app: 0|req: 1/5] 167.248.133.62 () {26 vars in 349 bytes} [Mon Oct 31 09:25:05 2022] GET / => generated 327 bytes in 65 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 30809|app: 0|req: 3/6] 167.248.133.62 () {18 vars in 183 bytes} [Mon Oct 31 09:25:06 2022] PRI * => generated 233 bytes in 32 msecs (HTTP/2.0 404) 5 headers in 154 bytes (1 switches on core 1)
[pid: 30809|app: 0|req: 4/7] 167.248.133.62 () {26 vars in 377 bytes} [Mon Oct 31 09:25:06 2022] GET /favicon.ico => generated 233 bytes in 1 msecs (HTTP/1.1 404) 5 headers in 154 bytes (1 switches on core 0)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 2 seconds
worker 2 buried after 2 seconds
worker 3 buried after 2 seconds
worker 4 buried after 2 seconds
goodbye to uWSGI.
!!! uWSGI process 30769 got Segmentation Fault !!!
*** backtrace of 30769 ***
*** end of backtrace ***
*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 09:26:00 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.30.1.26:5000 fd 3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Python main interpreter initialized at 0x54c468
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 359920 bytes (351 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x54c468 pid: 31078 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 31078)
spawned uWSGI worker 1 (pid: 31082, cores: 2)
spawned uWSGI worker 2 (pid: 31084, cores: 2)
spawned uWSGI worker 3 (pid: 31086, cores: 2)
spawned uWSGI worker 4 (pid: 31088, cores: 2)
[pid: 31084|app: 0|req: 1/1] 121.133.232.153 () {32 vars in 655 bytes} [Mon Oct 31 09:26:14 2022] GET / => generated 327 bytes in 60 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 31086|app: 0|req: 1/2] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 09:26:15 2022] GET /get_cam => generated 462 bytes in 61 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 31088|app: 0|req: 1/3] 121.133.232.153 () {34 vars in 679 bytes} [Mon Oct 31 09:26:33 2022] GET / => generated 327 bytes in 38 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 31088|app: 0|req: 2/4] 121.133.232.153 () {32 vars in 655 bytes} [Mon Oct 31 09:26:33 2022] GET / => generated 327 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
[pid: 31088|app: 0|req: 3/5] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 09:26:35 2022] GET /get_cam => generated 462 bytes in 7 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 870, in __next__
    return self._next()
  File "/usr/lib/python3/dist-packages/werkzeug/wrappers.py", line 82, in _iter_encoded
    for item in iterable:
  File "./raspi_web.py", line 20, in gen
    camera = RealSense()
  File "./realsense.py", line 18, in __init__
    self.pipeline.start(config)
RuntimeError: failed to set power state
[pid: 31086|app: 0|req: 2/6] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 09:26:36 2022] GET /video_feed => generated 0 bytes in 1951 msecs (HTTP/1.1 200) 4 headers in 158 bytes (0 switches on core 1)
SIGINT/SIGTERM received...killing workers...
!!! uWSGI process 31082 got Segmentation Fault !!!
*** backtrace of 31082 ***
*** end of backtrace ***
Exception ignored in: <function RealSense.__del__ at 0xa59cdf60>
Traceback (most recent call last):
  File "./realsense.py", line 21, in __del__
    self.pipeline.stop()
RuntimeError: stop() cannot be called before start()
worker 1 buried after 1 seconds
Mon Oct 31 09:27:48 2022 - worker 2 (pid: 31084) is taking too much time to die...NO MERCY !!!
Mon Oct 31 09:27:48 2022 - worker 3 (pid: 31086) is taking too much time to die...NO MERCY !!!
Mon Oct 31 09:27:48 2022 - worker 4 (pid: 31088) is taking too much time to die...NO MERCY !!!
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 09:28:17 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.30.1.26:5000 fd 3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Python main interpreter initialized at 0x18c1468
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 359920 bytes (351 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x18c1468 pid: 31447 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 31447)
spawned uWSGI worker 1 (pid: 31452, cores: 2)
spawned uWSGI worker 2 (pid: 31454, cores: 2)
spawned uWSGI worker 3 (pid: 31456, cores: 2)
spawned uWSGI worker 4 (pid: 31458, cores: 2)
[pid: 31456|app: 0|req: 1/1] 121.133.232.153 () {34 vars in 686 bytes} [Mon Oct 31 09:28:21 2022] GET / => generated 327 bytes in 26 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 31454|app: 0|req: 1/2] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 09:28:22 2022] GET /get_cam => generated 462 bytes in 55 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 31458|app: 0|req: 1/3] 121.133.232.153 () {34 vars in 704 bytes} [Mon Oct 31 09:28:42 2022] GET / => generated 327 bytes in 34 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
Mon Oct 31 09:28:42 2022 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed (121.133.232.153)
OSError: write error
[pid: 31454|app: 0|req: 2/4] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 09:29:00 2022] GET /get_cam => generated 462 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
SIGINT/SIGTERM received...killing workers...
!!! uWSGI process 31454 got Segmentation Fault !!!
*** backtrace of 31454 ***
*** end of backtrace ***
worker 2 buried after 1 seconds
worker 3 buried after 2 seconds
Mon Oct 31 09:30:14 2022 - worker 1 (pid: 31452) is taking too much time to die...NO MERCY !!!
Mon Oct 31 09:30:14 2022 - worker 4 (pid: 31458) is taking too much time to die...NO MERCY !!!
worker 1 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 09:35:46 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.30.1.26:5000 fd 3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Python main interpreter initialized at 0x11bc468
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 359920 bytes (351 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x11bc468 pid: 31845 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 31845)
spawned uWSGI worker 1 (pid: 31848, cores: 2)
spawned uWSGI worker 2 (pid: 31850, cores: 2)
spawned uWSGI worker 3 (pid: 31852, cores: 2)
spawned uWSGI worker 4 (pid: 31854, cores: 2)
[pid: 31850|app: 0|req: 1/1] 121.133.232.153 () {36 vars in 742 bytes} [Mon Oct 31 09:35:50 2022] GET /get_cam => generated 462 bytes in 75 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 31854|app: 0|req: 1/2] 121.133.232.153 () {34 vars in 679 bytes} [Mon Oct 31 09:35:56 2022] GET / => generated 327 bytes in 45 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 31852|app: 0|req: 2/3] 121.133.232.153 () {32 vars in 655 bytes} [Mon Oct 31 09:35:57 2022] GET / => generated 327 bytes in 22 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
[pid: 31852|app: 0|req: 3/4] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 09:35:58 2022] GET /get_cam => generated 462 bytes in 7 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
[2022-10-31 09:36:01,066] ERROR in app: Exception on /video_feed [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./raspi_web.py", line 34, in video_feed
    return Response(gen(RealSense()), mimetype='multipart/x-mixed-replace; boundary=frame')
  File "./realsense.py", line 19, in __init__
    self.pipeline.start(config)
RuntimeError: failed to set power state
[pid: 31854|app: 0|req: 2/5] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 09:35:58 2022] GET /video_feed => generated 291 bytes in 2186 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 1)
[pid: 31852|app: 0|req: 4/6] 121.133.232.153 () {36 vars in 742 bytes} [Mon Oct 31 09:36:10 2022] GET /get_cam => generated 462 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
[2022-10-31 09:36:13,085] ERROR in app: Exception on /video_feed [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./raspi_web.py", line 34, in video_feed
    return Response(gen(RealSense()), mimetype='multipart/x-mixed-replace; boundary=frame')
  File "./realsense.py", line 19, in __init__
    self.pipeline.start(config)
RuntimeError: failed to set power state
[pid: 31854|app: 0|req: 3/7] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 09:36:11 2022] GET /video_feed => generated 291 bytes in 2020 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
[pid: 31854|app: 0|req: 4/8] 121.133.232.153 () {34 vars in 704 bytes} [Mon Oct 31 10:22:59 2022] GET / => generated 327 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
Mon Oct 31 10:23:00 2022 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
Mon Oct 31 10:23:00 2022 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed (121.133.232.153)
OSError: write error
SIGINT/SIGTERM received...killing workers...
Exception ignored in: <function RealSense.__del__ at 0xa5168030>
Traceback (most recent call last):
  File "./realsense.py", line 22, in __del__
    def __del__(self):
RuntimeError: stop() cannot be called before start()
Exception ignored in: <function RealSense.__del__ at 0xa5168030>
Traceback (most recent call last):
  File "./realsense.py", line 22, in __del__
    def __del__(self):
RuntimeError: stop() cannot be called before start()
worker 3 buried after 2 seconds
Mon Oct 31 10:39:46 2022 - worker 1 (pid: 31848) is taking too much time to die...NO MERCY !!!
Mon Oct 31 10:39:46 2022 - worker 2 (pid: 31850) is taking too much time to die...NO MERCY !!!
Mon Oct 31 10:39:46 2022 - worker 4 (pid: 31854) is taking too much time to die...NO MERCY !!!
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 11:01:15 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.30.1.26:5000 fd 3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Python main interpreter initialized at 0x1b90468
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 359920 bytes (351 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x1b90468 pid: 2247 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2247)
spawned uWSGI worker 1 (pid: 2282, cores: 2)
spawned uWSGI worker 2 (pid: 2284, cores: 2)
spawned uWSGI worker 3 (pid: 2286, cores: 2)
spawned uWSGI worker 4 (pid: 2288, cores: 2)
[pid: 2284|app: 0|req: 1/1] 121.133.232.153 () {36 vars in 735 bytes} [Mon Oct 31 11:01:24 2022] GET / => generated 327 bytes in 40 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 2288|app: 0|req: 1/2] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 11:01:26 2022] GET /get_cam => generated 462 bytes in 43 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 870, in __next__
    return self._next()
  File "/usr/lib/python3/dist-packages/werkzeug/wrappers.py", line 82, in _iter_encoded
    for item in iterable:
  File "./raspi_web.py", line 19, in gen
    frame = camera.get_numpy_color_image()
  File "./realsense.py", line 43, in get_numpy_color_image
    frames = RealSense.pipeline.wait_for_frames()
RuntimeError: Frame didn't arrive within 5000
[pid: 2288|app: 0|req: 2/3] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 11:01:26 2022] GET /video_feed => generated 0 bytes in 5015 msecs (HTTP/1.1 200) 4 headers in 158 bytes (0 switches on core 1)
[pid: 2288|app: 0|req: 3/4] 121.133.232.153 () {36 vars in 742 bytes} [Mon Oct 31 11:02:05 2022] GET /get_cam => generated 462 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 2286|app: 0|req: 1/5] 121.133.232.153 () {36 vars in 742 bytes} [Mon Oct 31 11:02:29 2022] GET /get_cam => generated 462 bytes in 52 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 2 seconds
worker 2 buried after 2 seconds
worker 3 buried after 2 seconds
worker 4 buried after 2 seconds
goodbye to uWSGI.
!!! uWSGI process 2247 got Segmentation Fault !!!
*** backtrace of 2247 ***
*** end of backtrace ***
*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 11:04:50 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.30.1.26:5000 fd 3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Python main interpreter initialized at 0x1dfe468
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 359920 bytes (351 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x1dfe468 pid: 2509 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2509)
spawned uWSGI worker 1 (pid: 2537, cores: 2)
spawned uWSGI worker 2 (pid: 2539, cores: 2)
spawned uWSGI worker 3 (pid: 2541, cores: 2)
spawned uWSGI worker 4 (pid: 2543, cores: 2)
[pid: 2543|app: 0|req: 1/1] 121.133.232.153 () {36 vars in 742 bytes} [Mon Oct 31 11:04:54 2022] GET /get_cam => generated 462 bytes in 46 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "./realsense.py", line 44, in get_numpy_color_image
    frames = RealSense.pipeline.wait_for_frames()
RuntimeError: Frame didn't arrive within 5000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 870, in __next__
    return self._next()
  File "/usr/lib/python3/dist-packages/werkzeug/wrappers.py", line 82, in _iter_encoded
    for item in iterable:
  File "./raspi_web.py", line 19, in gen
    frame = camera.get_numpy_color_image()
  File "./realsense.py", line 46, in get_numpy_color_image
    frames = RealSense.pipeline.wait_for_frames()
RuntimeError: Frame didn't arrive within 5000
[pid: 2537|app: 0|req: 1/2] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 11:04:55 2022] GET /video_feed => generated 0 bytes in 10034 msecs (HTTP/1.1 200) 4 headers in 158 bytes (0 switches on core 0)
[pid: 2537|app: 0|req: 2/3] 121.133.232.153 () {34 vars in 704 bytes} [Mon Oct 31 11:05:45 2022] GET / => generated 327 bytes in 31 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
SIGINT/SIGTERM received...killing workers...
worker 2 buried after 2 seconds
worker 3 buried after 2 seconds
worker 4 buried after 2 seconds
Mon Oct 31 12:40:02 2022 - worker 1 (pid: 2537) is taking too much time to die...NO MERCY !!!
worker 1 buried after 1 seconds
goodbye to uWSGI.
!!! uWSGI process 2509 got Segmentation Fault !!!
*** backtrace of 2509 ***
*** end of backtrace ***
*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 12:42:11 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.30.1.26:5000 fd 3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Python main interpreter initialized at 0x134f468
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 359920 bytes (351 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x134f468 pid: 6357 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 6357)
spawned uWSGI worker 1 (pid: 6366, cores: 2)
spawned uWSGI worker 2 (pid: 6368, cores: 2)
spawned uWSGI worker 3 (pid: 6370, cores: 2)
spawned uWSGI worker 4 (pid: 6372, cores: 2)
[pid: 6370|app: 0|req: 1/1] 121.133.232.153 () {36 vars in 735 bytes} [Mon Oct 31 12:42:16 2022] GET / => generated 327 bytes in 60 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 6368|app: 0|req: 1/2] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 12:42:18 2022] GET /get_cam => generated 462 bytes in 52 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
OpenCV Error: Unknown error code -10 (Raw image encoder error: Empty JPEG image (DNL not supported)) in throwOnEror, file /build/opencv-L65chJ/opencv-3.2.0+dfsg/modules/imgcodecs/src/grfmt_base.cpp, line 139
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 870, in __next__
    return self._next()
  File "/usr/lib/python3/dist-packages/werkzeug/wrappers.py", line 82, in _iter_encoded
    for item in iterable:
  File "./raspi_web.py", line 22, in gen
    _, frame = cv2.imencode('.jpg', frame)
cv2.error: /build/opencv-L65chJ/opencv-3.2.0+dfsg/modules/imgcodecs/src/grfmt_base.cpp:139: error: (-10) Raw image encoder error: Empty JPEG image (DNL not supported) in function throwOnEror

[pid: 6368|app: 0|req: 2/3] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 12:42:18 2022] GET /video_feed => generated 0 bytes in 444 msecs (HTTP/1.1 200) 4 headers in 158 bytes (0 switches on core 1)
SIGINT/SIGTERM received...killing workers...
worker 2 buried after 1 seconds
Mon Oct 31 12:44:00 2022 - worker 1 (pid: 6366) is taking too much time to die...NO MERCY !!!
Mon Oct 31 12:44:00 2022 - worker 3 (pid: 6370) is taking too much time to die...NO MERCY !!!
Mon Oct 31 12:44:00 2022 - worker 4 (pid: 6372) is taking too much time to die...NO MERCY !!!
worker 1 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 12:52:04 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.30.1.26:5000 fd 3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Python main interpreter initialized at 0x28c468
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 359920 bytes (351 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x28c468 pid: 6688 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 6688)
spawned uWSGI worker 1 (pid: 6693, cores: 2)
spawned uWSGI worker 2 (pid: 6695, cores: 2)
spawned uWSGI worker 3 (pid: 6697, cores: 2)
spawned uWSGI worker 4 (pid: 6699, cores: 2)
[pid: 6697|app: 0|req: 1/1] 121.133.232.153 () {34 vars in 686 bytes} [Mon Oct 31 12:52:07 2022] GET / => generated 327 bytes in 38 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 6699|app: 0|req: 1/2] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 12:52:10 2022] GET /get_cam => generated 462 bytes in 69 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 6697|app: 0|req: 2/3] 121.133.232.153 () {34 vars in 704 bytes} [Mon Oct 31 12:52:25 2022] GET / => generated 327 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
Mon Oct 31 12:52:26 2022 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed (121.133.232.153)
OSError: write error
[pid: 6699|app: 0|req: 2/4] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 12:52:11 2022] GET /video_feed => generated 67588854 bytes in 14822 msecs (HTTP/1.1 200) 4 headers in 158 bytes (1338 switches on core 1)
[pid: 6697|app: 0|req: 3/5] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 12:52:45 2022] GET /get_cam => generated 462 bytes in 11 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[2022-10-31 12:52:47,760] ERROR in app: Exception on /video_feed [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./raspi_web.py", line 36, in video_feed
    return Response(gen(RealSense()), mimetype='multipart/x-mixed-replace; boundary=frame')
  File "./realsense.py", line 38, in __init__
    self.pipeline.start(config)
RuntimeError: failed to set power state
[pid: 6699|app: 0|req: 3/6] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 12:52:46 2022] GET /video_feed => generated 291 bytes in 1618 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
[pid: 6699|app: 0|req: 4/7] 121.133.232.153 () {36 vars in 742 bytes} [Mon Oct 31 12:52:49 2022] GET /get_cam => generated 462 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
[2022-10-31 12:52:51,079] ERROR in app: Exception on /video_feed [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./raspi_web.py", line 36, in video_feed
    return Response(gen(RealSense()), mimetype='multipart/x-mixed-replace; boundary=frame')
  File "./realsense.py", line 38, in __init__
    self.pipeline.start(config)
RuntimeError: failed to set power state
[pid: 6695|app: 0|req: 1/8] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 12:52:49 2022] GET /video_feed => generated 291 bytes in 1598 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
SIGINT/SIGTERM received...killing workers...
Exception ignored in: <function RealSense.__del__ at 0xa59d2fa8>
Traceback (most recent call last):
  File "./realsense.py", line 43, in __del__
    self.pipeline.stop()
RuntimeError: stop() cannot be called before start()
Exception ignored in: <function RealSense.__del__ at 0xa59d2fa8>
Traceback (most recent call last):
  File "./realsense.py", line 43, in __del__
    self.pipeline.stop()
RuntimeError: stop() cannot be called before start()
worker 4 buried after 1 seconds
Mon Oct 31 12:55:01 2022 - worker 1 (pid: 6693) is taking too much time to die...NO MERCY !!!
Mon Oct 31 12:55:01 2022 - worker 2 (pid: 6695) is taking too much time to die...NO MERCY !!!
Mon Oct 31 12:55:01 2022 - worker 3 (pid: 6697) is taking too much time to die...NO MERCY !!!
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 12:56:31 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.30.1.26:5000 fd 3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Python main interpreter initialized at 0x88e468
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 359920 bytes (351 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x88e468 pid: 7161 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 7161)
spawned uWSGI worker 1 (pid: 7168, cores: 2)
spawned uWSGI worker 2 (pid: 7170, cores: 2)
spawned uWSGI worker 3 (pid: 7172, cores: 2)
spawned uWSGI worker 4 (pid: 7174, cores: 2)
[pid: 7170|app: 0|req: 1/1] 121.133.232.153 () {34 vars in 679 bytes} [Mon Oct 31 12:56:35 2022] GET / => generated 327 bytes in 60 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 7174|app: 0|req: 1/2] 121.133.232.153 () {32 vars in 655 bytes} [Mon Oct 31 12:56:36 2022] GET / => generated 327 bytes in 26 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 7168|app: 0|req: 1/3] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 12:56:37 2022] GET /get_cam => generated 462 bytes in 64 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 7174|app: 0|req: 2/4] 121.133.232.153 () {34 vars in 704 bytes} [Mon Oct 31 12:57:14 2022] GET / => generated 327 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
[pid: 7174|app: 0|req: 3/5] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 12:57:26 2022] GET /get_cam => generated 462 bytes in 6 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[2022-10-31 12:57:27,345] ERROR in app: Exception on /video_feed [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./raspi_web.py", line 36, in video_feed
    return Response(gen(RealSense()), mimetype='multipart/x-mixed-replace; boundary=frame')
  File "./realsense.py", line 38, in __init__
    self.pipeline.start(config)
RuntimeError: failed to set power state
[pid: 7174|app: 0|req: 4/6] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 12:57:26 2022] GET /video_feed => generated 291 bytes in 598 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 1)
SIGINT/SIGTERM received...killing workers...
Exception ignored in: <function RealSense.__del__ at 0xa59d1fa8>
Traceback (most recent call last):
  File "./realsense.py", line 47, in __del__
    self.cam_thread.join()
AttributeError: 'RealSense' object has no attribute 'cam_thread'
worker 2 buried after 2 seconds
Mon Oct 31 12:58:54 2022 - worker 1 (pid: 7168) is taking too much time to die...NO MERCY !!!
Mon Oct 31 12:58:54 2022 - worker 3 (pid: 7172) is taking too much time to die...NO MERCY !!!
Mon Oct 31 12:58:54 2022 - worker 4 (pid: 7174) is taking too much time to die...NO MERCY !!!
worker 1 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 12:59:21 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.30.1.26:5000 fd 3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Python main interpreter initialized at 0x20f4468
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 359920 bytes (351 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x20f4468 pid: 7390 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 7390)
spawned uWSGI worker 1 (pid: 7393, cores: 2)
spawned uWSGI worker 2 (pid: 7395, cores: 2)
spawned uWSGI worker 3 (pid: 7397, cores: 2)
spawned uWSGI worker 4 (pid: 7399, cores: 2)
[pid: 7395|app: 0|req: 1/1] 121.133.232.153 () {34 vars in 686 bytes} [Mon Oct 31 12:59:53 2022] GET / => generated 327 bytes in 63 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 7395|app: 0|req: 2/2] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 12:59:55 2022] GET /get_cam => generated 462 bytes in 15 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
RealSense Generate
[pid: 7395|app: 0|req: 3/3] 121.133.232.153 () {32 vars in 655 bytes} [Mon Oct 31 13:00:23 2022] GET / => generated 327 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
Mon Oct 31 13:00:23 2022 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
Mon Oct 31 13:00:23 2022 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed (121.133.232.153)
OSError: write error
[pid: 7399|app: 0|req: 1/4] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 13:00:36 2022] GET /get_cam => generated 462 bytes in 30 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
RealSense Generate
[pid: 7399|app: 0|req: 3/5] 121.133.232.153 () {32 vars in 655 bytes} [Mon Oct 31 13:01:02 2022] GET / => generated 327 bytes in 3 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
Mon Oct 31 13:01:02 2022 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed (121.133.232.153)
OSError: write error
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 2 seconds
worker 4 buried after 2 seconds
Mon Oct 31 13:02:08 2022 - worker 2 (pid: 7395) is taking too much time to die...NO MERCY !!!
Mon Oct 31 13:02:08 2022 - worker 3 (pid: 7397) is taking too much time to die...NO MERCY !!!
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 13:03:15 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.30.1.26:5000 fd 3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Python main interpreter initialized at 0x814468
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 359920 bytes (351 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x814468 pid: 7637 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 7637)
spawned uWSGI worker 1 (pid: 7644, cores: 2)
spawned uWSGI worker 2 (pid: 7646, cores: 2)
spawned uWSGI worker 3 (pid: 7648, cores: 2)
spawned uWSGI worker 4 (pid: 7650, cores: 2)
[pid: 7646|app: 0|req: 1/1] 121.133.232.153 () {34 vars in 686 bytes} [Mon Oct 31 13:03:19 2022] GET / => generated 327 bytes in 52 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 7646|app: 0|req: 2/2] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 13:03:20 2022] GET /get_cam => generated 462 bytes in 13 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
RealSense init
[pid: 7646|app: 0|req: 4/3] 121.133.232.153 () {34 vars in 704 bytes} [Mon Oct 31 13:03:25 2022] GET / => generated 327 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
Mon Oct 31 13:03:25 2022 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
Mon Oct 31 13:03:25 2022 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed (121.133.232.153)
OSError: write error
RealSense del
[pid: 7650|app: 0|req: 1/4] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 13:03:29 2022] GET /get_cam => generated 462 bytes in 30 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 7644|app: 0|req: 1/5] 121.133.232.153 () {36 vars in 742 bytes} [Mon Oct 31 13:03:34 2022] GET /get_cam => generated 462 bytes in 30 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
RealSense init
[pid: 7650|app: 0|req: 2/6] 121.133.232.153 () {34 vars in 704 bytes} [Mon Oct 31 13:03:37 2022] GET / => generated 327 bytes in 4 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
Mon Oct 31 13:03:37 2022 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed (121.133.232.153)
OSError: write error
RealSense del
SIGINT/SIGTERM received...killing workers...
worker 2 buried after 1 seconds
worker 1 buried after 2 seconds
*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 13:14:12 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.30.1.26:5000 fd 3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Python main interpreter initialized at 0x174468
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 359920 bytes (351 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x174468 pid: 8062 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 8062)
spawned uWSGI worker 1 (pid: 8067, cores: 2)
spawned uWSGI worker 2 (pid: 8069, cores: 2)
spawned uWSGI worker 3 (pid: 8071, cores: 2)
spawned uWSGI worker 4 (pid: 8073, cores: 2)
[pid: 8071|app: 0|req: 1/1] 121.133.232.153 () {36 vars in 735 bytes} [Mon Oct 31 13:14:16 2022] GET / => generated 327 bytes in 61 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 8067|app: 0|req: 1/2] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 13:14:17 2022] GET /get_cam => generated 462 bytes in 59 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
RealSense init
[pid: 8071|app: 0|req: 2/3] 121.133.232.153 () {34 vars in 704 bytes} [Mon Oct 31 13:15:33 2022] GET / => generated 327 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
Mon Oct 31 13:15:33 2022 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
Mon Oct 31 13:15:33 2022 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed (121.133.232.153)
OSError: write error
[pid: 8069|app: 0|req: 1/4] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 13:14:17 2022] GET /video_feed => generated 347120075 bytes in 75661 msecs (HTTP/1.1 200) 4 headers in 158 bytes (6714 switches on core 0)
[pid: 8071|app: 0|req: 3/5] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 13:16:17 2022] GET /get_cam => generated 462 bytes in 10 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
RealSense init
[2022-10-31 13:16:19,448] ERROR in app: Exception on /video_feed [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./raspi_web.py", line 36, in video_feed
    return Response(gen(RealSense()), mimetype='multipart/x-mixed-replace; boundary=frame')
  File "./realsense.py", line 41, in __init__
    self.pipeline.start(config)
RuntimeError: failed to set power state
[pid: 8073|app: 0|req: 1/6] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 13:16:17 2022] GET /video_feed => generated 291 bytes in 1592 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
SIGINT/SIGTERM received...killing workers...
RealSense del
Exception ignored in: <function RealSense.__del__ at 0xa59dafa8>
Traceback (most recent call last):
  File "./realsense.py", line 51, in __del__
    self.cam_thread.join()
AttributeError: 'RealSense' object has no attribute 'cam_thread'
Mon Oct 31 13:17:41 2022 - worker 1 (pid: 8067) is taking too much time to die...NO MERCY !!!
Mon Oct 31 13:17:41 2022 - worker 2 (pid: 8069) is taking too much time to die...NO MERCY !!!
Mon Oct 31 13:17:41 2022 - worker 3 (pid: 8071) is taking too much time to die...NO MERCY !!!
Mon Oct 31 13:17:41 2022 - worker 4 (pid: 8073) is taking too much time to die...NO MERCY !!!
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 13:30:26 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.30.1.26:5000 fd 3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Python main interpreter initialized at 0xfbe468
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 359920 bytes (351 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0xfbe468 pid: 9692 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9692)
spawned uWSGI worker 1 (pid: 9695, cores: 2)
spawned uWSGI worker 2 (pid: 9697, cores: 2)
spawned uWSGI worker 3 (pid: 9700, cores: 2)
spawned uWSGI worker 4 (pid: 9702, cores: 2)
[pid: 9695|app: 0|req: 1/1] 121.133.232.153 () {34 vars in 679 bytes} [Mon Oct 31 13:30:34 2022] GET / => generated 327 bytes in 53 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 9700|app: 0|req: 1/2] 121.133.232.153 () {32 vars in 655 bytes} [Mon Oct 31 13:30:34 2022] GET / => generated 327 bytes in 60 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 9697|app: 0|req: 1/3] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 13:30:35 2022] GET /get_cam => generated 462 bytes in 61 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
RealSense init
This is gen() function
[pid: 9700|app: 0|req: 2/4] 121.133.232.153 () {34 vars in 704 bytes} [Mon Oct 31 13:30:38 2022] GET / => generated 327 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
Mon Oct 31 13:30:38 2022 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed (121.133.232.153)
OSError: write error
[pid: 9697|app: 0|req: 2/5] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 13:30:36 2022] GET /video_feed => generated 6403795 bytes in 2243 msecs (HTTP/1.1 200) 4 headers in 158 bytes (161 switches on core 1)
[pid: 9700|app: 0|req: 3/6] 121.133.232.153 () {36 vars in 735 bytes} [Mon Oct 31 13:30:40 2022] GET / => generated 327 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 9702|app: 0|req: 1/7] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 13:30:41 2022] GET /get_cam => generated 462 bytes in 50 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
RealSense init
[2022-10-31 13:30:43,823] ERROR in app: Exception on /video_feed [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./raspi_web.py", line 37, in video_feed
    return Response(gen(RealSense()), mimetype='multipart/x-mixed-replace; boundary=frame')
  File "./realsense.py", line 41, in __init__
    self.pipeline.start(config)
RuntimeError: failed to set power state
[pid: 9702|app: 0|req: 2/8] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 13:30:42 2022] GET /video_feed => generated 291 bytes in 1602 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 1)
[pid: 9700|app: 0|req: 4/9] 121.133.232.153 () {36 vars in 742 bytes} [Mon Oct 31 13:30:45 2022] GET /get_cam => generated 462 bytes in 11 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
RealSense init
[2022-10-31 13:30:47,104] ERROR in app: Exception on /video_feed [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./raspi_web.py", line 37, in video_feed
    return Response(gen(RealSense()), mimetype='multipart/x-mixed-replace; boundary=frame')
  File "./realsense.py", line 41, in __init__
    self.pipeline.start(config)
RuntimeError: failed to set power state
[pid: 9702|app: 0|req: 3/10] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 13:30:45 2022] GET /video_feed => generated 291 bytes in 1456 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
[pid: 9702|app: 0|req: 4/11] 121.133.232.153 () {34 vars in 704 bytes} [Mon Oct 31 13:30:48 2022] GET / => generated 327 bytes in 4 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
SIGINT/SIGTERM received...killing workers...
RealSense del
RealSense del
worker 2 buried after 1 seconds
Mon Oct 31 13:32:26 2022 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Mon Oct 31 13:32:26 2022 - uWSGI worker 4 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 13:32:40 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.30.1.26:5000 fd 3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Python main interpreter initialized at 0xbf5468
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 359920 bytes (351 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0xbf5468 pid: 10137 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 10137)
spawned uWSGI worker 1 (pid: 10142, cores: 2)
spawned uWSGI worker 2 (pid: 10144, cores: 2)
spawned uWSGI worker 3 (pid: 10146, cores: 2)
spawned uWSGI worker 4 (pid: 10148, cores: 2)
[pid: 10146|app: 0|req: 1/1] 121.133.232.153 () {36 vars in 735 bytes} [Mon Oct 31 13:32:44 2022] GET / => generated 327 bytes in 54 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
[pid: 10142|app: 0|req: 1/2] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 13:32:45 2022] GET /get_cam => generated 462 bytes in 69 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
RealSense init
This is gen() function
[pid: 10142|app: 0|req: 3/3] 121.133.232.153 () {34 vars in 704 bytes} [Mon Oct 31 13:32:47 2022] GET / => generated 327 bytes in 3 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
Mon Oct 31 13:32:47 2022 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed (121.133.232.153)
OSError: write error
RealSense del
[pid: 10146|app: 0|req: 2/4] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 13:32:53 2022] GET /get_cam => generated 462 bytes in 7 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 1)
RealSense init
This is gen() function
[pid: 10148|app: 0|req: 1/5] 121.133.232.153 () {34 vars in 704 bytes} [Mon Oct 31 13:32:55 2022] GET / => generated 327 bytes in 29 msecs (HTTP/1.1 200) 5 headers in 162 bytes (1 switches on core 0)
Mon Oct 31 13:32:56 2022 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
Mon Oct 31 13:32:56 2022 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed (121.133.232.153)
OSError: write error
RealSense del
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 2 seconds
worker 3 buried after 2 seconds
Mon Oct 31 13:36:02 2022 - uWSGI worker 4 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 13:36:12 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.30.1.26:5000 fd 3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Python main interpreter initialized at 0x150d468
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 359920 bytes (351 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
RealSense init
*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 13:43:57 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.30.1.26:5000 fd 3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Python main interpreter initialized at 0xc7c468
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 359920 bytes (351 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from raspi_web import app
  File "./raspi_web.py", line 10, in <module>
    cam = RealSense().start()
AttributeError: 'RealSense' object has no attribute 'start'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 11058)
spawned uWSGI worker 1 (pid: 11086, cores: 2)
--- no python application found, check your startup logs for errors ---
[pid: 11086|app: -1|req: -1/1] 121.133.232.153 () {36 vars in 735 bytes} [Mon Oct 31 13:44:00 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
spawned uWSGI worker 2 (pid: 11088, cores: 2)
spawned uWSGI worker 3 (pid: 11090, cores: 2)
spawned uWSGI worker 4 (pid: 11092, cores: 2)
--- no python application found, check your startup logs for errors ---
[pid: 11090|app: -1|req: -1/2] 121.133.232.153 () {36 vars in 735 bytes} [Mon Oct 31 13:44:02 2022] GET / => generated 21 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 13:44:44 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (172.30.1.26:5000).
bind(): Address already in use [core/socket.c line 769]
--- no python application found, check your startup logs for errors ---
[pid: 11092|app: -1|req: -1/3] 121.133.232.153 () {36 vars in 735 bytes} [Mon Oct 31 13:44:49 2022] GET / => generated 21 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 11090|app: -1|req: -1/4] 121.133.232.153 () {36 vars in 735 bytes} [Mon Oct 31 13:44:50 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
Mon Oct 31 13:45:16 2022 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Mon Oct 31 13:45:16 2022 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Mon Oct 31 13:45:16 2022 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Mon Oct 31 13:45:16 2022 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Mon Oct 31 13:45:16 2022 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Mon Oct 31 13:45:16 2022 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Mon Oct 31 13:45:16 2022 - uWSGI worker 4 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Mon Oct 31 13:45:17 2022 - uWSGI worker 4 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.20 (32bit) on [Mon Oct 31 13:45:43 2022] ***
compiled with version: 8.3.0 on 06 October 2021 05:59:48
os: Linux-5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/michael/myungsang/Raspberry-Projects/home_cctv
writing pidfile to /home/michael/myungsang/Raspberry-Projects/home_cctv/uwsgi.pid
detected binary path: /home/michael/.local/bin/uwsgi
your processes number limit is 28133
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 172.30.1.26:5000 fd 3
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Python main interpreter initialized at 0x20c9468
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 359920 bytes (351 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x20c9468 pid: 11211 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 11211)
spawned uWSGI worker 1 (pid: 11216, cores: 2)
spawned uWSGI worker 2 (pid: 11218, cores: 2)
spawned uWSGI worker 3 (pid: 11220, cores: 2)
spawned uWSGI worker 4 (pid: 11222, cores: 2)
[pid: 11216|app: 0|req: 1/1] 121.133.232.153 () {36 vars in 735 bytes} [Mon Oct 31 13:45:46 2022] GET / => generated 327 bytes in 32 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 11216|app: 0|req: 2/2] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 13:45:47 2022] GET /get_cam => generated 462 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 1)
[pid: 11216|app: 0|req: 4/3] 121.133.232.153 () {34 vars in 704 bytes} [Mon Oct 31 13:46:04 2022] GET / => generated 327 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 1)
Mon Oct 31 13:46:04 2022 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
Mon Oct 31 13:46:04 2022 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed (121.133.232.153)
OSError: write error
[pid: 11222|app: 0|req: 1/4] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 13:46:12 2022] GET /get_cam => generated 462 bytes in 30 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 11222|app: 0|req: 3/5] 121.133.232.153 () {34 vars in 679 bytes} [Mon Oct 31 13:46:25 2022] GET / => generated 327 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 11222|app: 0|req: 4/6] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 13:46:31 2022] GET /get_cam => generated 462 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 11222|app: 0|req: 5/7] 121.133.232.153 () {36 vars in 742 bytes} [Mon Oct 31 13:46:51 2022] GET /get_cam => generated 462 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[2022-10-31 13:46:53,791] ERROR in app: Exception on /video_feed [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./raspi_web.py", line 34, in video_feed
    return Response(gen(RealSense()), mimetype='multipart/x-mixed-replace; boundary=frame')
  File "./realsense.py", line 18, in __init__
    self.pipeline.start(config)
RuntimeError: failed to set power state
[pid: 11222|app: 0|req: 6/8] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 13:46:51 2022] GET /video_feed => generated 291 bytes in 1858 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
[pid: 11222|app: 0|req: 7/9] 121.133.232.153 () {34 vars in 704 bytes} [Mon Oct 31 13:47:04 2022] GET / => generated 327 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
OSError: write error
[pid: 11222|app: 0|req: 7/10] 121.133.232.153 () {32 vars in 618 bytes} [Mon Oct 31 13:46:12 2022] GET /video_feed => generated 229352971 bytes in 51769 msecs (HTTP/1.1 200) 1 headers in 76 bytes (1273 switches on core 1)
[pid: 11222|app: 0|req: 8/11] 121.133.232.153 () {34 vars in 711 bytes} [Mon Oct 31 13:47:12 2022] GET /get_cam => generated 462 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 0)
[pid: 11222|app: 0|req: 9/12] 121.133.232.153 () {34 vars in 704 bytes} [Mon Oct 31 13:47:14 2022] GET / => generated 327 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1 switches on core 1)
Mon Oct 31 13:47:15 2022 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
Mon Oct 31 13:47:15 2022 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed (121.133.232.153)
OSError: write error
SIGINT/SIGTERM received...killing workers...
Exception ignored in: <function RealSense.__del__ at 0xa59fffa8>
Traceback (most recent call last):
  File "./realsense.py", line 21, in __del__
    self.pipeline.stop()
RuntimeError: stop() cannot be called before start()
worker 1 buried after 1 seconds
worker 3 buried after 2 seconds
Mon Oct 31 13:48:21 2022 - worker 2 (pid: 11218) is taking too much time to die...NO MERCY !!!
Mon Oct 31 13:48:21 2022 - worker 4 (pid: 11222) is taking too much time to die...NO MERCY !!!
worker 2 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
